web:
  resources-path: /ilohas
  api-path: /ilohas-api

spring:
  webflux:
    static-path-pattern: ${web.resources-path}/**
  resources:
    static-locations: classpath:/META-INF/resources/


ilohas:
  import:
    chunkSize: 100
    market:
      marketDataName: Official
      interestRate:
        fileName: InterestRate.csv
      fxSpotRate:
        fileName: FxSpotRate.csv
