web:
  resources-path: /ilohas
  api-path: /ilohas-api

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/test
    username:
    password:
  jpa.properties:
    hibernate:
      hbm2ddl.auto: create

  webflux:
    static-path-pattern: ${web.resources-path}/**
  resources:
    static-locations: classpath:/META-INF/resources/

  # for debugging
  cache.type: NONE

  # TODO temporary
  security.user.password: pass


ilohas:
  import:
    chunkSize: 100
    market:
      marketDataName: Official
      interestRate:
        fileName: InterestRate.csv
      fxSpotRate:
        fileName: FxSpotRate.csv
