spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/test
    username:
    password:
  jpa:
    hibernate:
      hbm2ddl.auto: create-drop


ilohas:
  import:
    chunkSize: 100
    market:
      marketDataName: Official
      interestRate:
        fileName: InterestRate.csv
      fxSpotRate:
        fileName: FxSpotRate.csv
