
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./temp/db/test
    username:
    password:
  jpa.properties:
    hibernate:
      hbm2ddl.auto: create-drop

  # for debugging
  cache.type: NONE
