
spring:
  jpa.properties:
    hibernate:
      hbm2ddl.auto: none

    javax.persistence.schema-generation.scripts:
      action: create-drop
      create-target: ./temp/ddl/create.sql
      drop-target: ./temp/ddl/drop.sql
